# Generated by Django 3.0.6 on 2020-05-21 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категорию оборудования',
                'verbose_name_plural': 'Категории оборудования',
            },
        ),
        migrations.CreateModel(
            name='Sellout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='sellout', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Акция',
                'verbose_name_plural': 'Акции',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Название')),
                ('description', models.TextField(max_length=1024, verbose_name='Описание')),
                ('size', models.CharField(max_length=256, verbose_name='Размер')),
                ('cost', models.PositiveSmallIntegerField(verbose_name='Цена')),
                ('cost_sale', models.PositiveSmallIntegerField(default=0, help_text='Если больше нуля, товар отображается в категории распродажа', verbose_name='Цена cо скидкой')),
                ('image', models.ImageField(upload_to='item', verbose_name='Изображение')),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='main.ItemCategory', verbose_name='Категория оборудования')),
            ],
            options={
                'verbose_name': 'Оборудование',
                'verbose_name_plural': 'Оборудование',
            },
        ),
    ]
