# Generated by Django 3.0.6 on 2020-05-21 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcategory',
            name='nested',
            field=models.ManyToManyField(blank=True, related_name='nestedCategory', to='main.ItemCategory', verbose_name='Подкатегории'),
        ),
    ]
