# Generated by Django 3.0.6 on 2020-05-23 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_itemcategory_nested'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='size',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Размер'),
        ),
    ]
